[package]
name = "http-client-tls"
edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

[lints]
workspace = true

[features]
test-support = []

[dependencies]
rustls.workspace = true
rustls-platform-verifier.workspace = true
