[package]
name = "paths"
edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

[lints]
workspace = true

[features]
test-support = []

[dependencies]
dirs.workspace = true
ignore.workspace = true
util.workspace = true
